name: database integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Allow SSH agent forwarding (for Dockerfile build if needed)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: mv .env.example .env

      - name: remove alembic versions
        run: rm -rf alembic/versions/*

      - name: create alembic migration from scratch
        run: docker compose run --rm database-migrations poetry run alembic revision --autogenerate -m "Initial migration"

      - name: Run integration tests
        run: docker compose run --rm database-migrations

      - name: Show logs (optional, for debugging)
        run: docker compose logs --no-color

      - name: Tear down
        if: always()
        run: docker compose down -v
